"""add best_price_seats_left to subscriptions

Revision ID: 445e6d0171f2
Revises: f0d8daf8ab0b
Create Date: 2026-05-27 19:30:22.583313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445e6d0171f2'
down_revision: Union[str, None] = 'f0d8daf8ab0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('best_price_seats_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'best_price_seats_left')
    # ### end Alembic commands ###
