"""add current_price to subscriptions

Revision ID: ba381df0e898
Revises: 1d7cda3b1998
Create Date: 2026-05-30 11:44:26.617591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba381df0e898'
down_revision: Union[str, None] = '1d7cda3b1998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_price')
    # ### end Alembic commands ###
